### ISSUE TITLE
WebhookController has an issue when parsing status in some cases

### ISSUE THREAD

**Issue by osmant** [docusign/recipe-010-webhook-csharp#1]
Hi,

When WebHookController post method is triggered by docusign, document status is captured. Most of the time captured status value is correct. But in some cases, it is returning incorrect value.

My test case is as following.
1- Send the document from Signature Request - Webhook tab
2- View events. Make sure the document is in sent status.
3- Login to docusign account and void the document.

In this case In view events section, I am getting new Docusign Connect XML. But the xml is pointing sent state XML.

I found the solution but I was unable to make pull request.

Following line inside WebHookController.cs
`XmlNode status = envelopeStatus.SelectSingleNode("//a:Status", mgr);`

should be changed with following 

`XmlNode status = envelopeStatus.SelectSingleNode("./a:Status", mgr);`

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report and fix! I will report the problem to the engineering group.

**Comment by gsnavin** [comment]
@osmant Thanks for pointing out the issue. I have made the requested change.
https://github.com/docusign/recipe-010-webhook-csharp/pull/2
